Repository Nein-to-Sick/bandi_official, pull requests merged in 2025-03, with the labels that each got.

#119 [Bug] 설정 페이지 버튼을 바 전체 클릭으로 변경
  lib/view/user/settings_home.dart
Labels: 🐛 BUG

#120 [Bug] 달력 년도 변경이 안되는 버그 해결
  lib/view/list/calendar.dart
Labels: 🐛 BUG

#121 [Bug] 스크롤 되는 설정 페이지, 계정 관리 페이지, 닉네임 페이지 스크롤 방지
  lib/view/user/account_management.dart
  lib/view/user/nickname_change.dart
  lib/view/user/settings_home.dart
Labels: 🐛 BUG

#122 [Refactoring] 사업자 주소 변경
  lib/model/settingsInfos.dart
Labels: documentation

#123 [Bug] 인터넷 연결시 에러 핸들링
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/controller/internet_connection_controller.dart
  lib/main.dart
  lib/view/navigation.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: 🐛 BUG

#129 [Feat] 알림 페이지 디자인 수정 및 삭제 기능 추가
  lib/controller/alarm_controller.dart
  lib/view/alarm/alarm_view.dart
  lib/view/navigation.dart
Labels: enhancement, Design
